// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackendApi.Data;

#nullable disable

namespace MyBackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008154123_AddAccountLockoutFields")]
    partial class AddAccountLockoutFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBackendApi.Models.Entities.BugReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("SystemModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("BugReports");
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.ErrorCatalog", b =>
                {
                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HebrewDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResolutionPlaybook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("SeverityLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subsystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ErrorCode");

                    b.ToTable("ErrorCatalogs", (string)null);

                    b.HasData(
                        new
                        {
                            ErrorCode = "CLIENT_NETWORK_DEGRADED",
                            Category = "Client-Side/Network",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "זוהתה האטה או אובדן חבילות ברשת בעמדת הלקוח (latency גבוה/ping נכשל) - מזוהה אוטומטית ע\"י בדיקת קישוריות בדפדפן",
                            ResolutionPlaybook = "1. לבדוק את יציבות חיבור הרשת (Wi-Fi/כבל) בעמדת הלקוח. 2. להפעיל מחדש את הנתב/המחשב. 3. אם ממשיך, לבדוק תחזוקה מתוכננת אצל ספק האינטרנט או VPN פעיל שמאט את התעבורה.",
                            SeverityLevel = (byte)2,
                            Subsystem = "WebClient",
                            TenantId = ""
                        },
                        new
                        {
                            ErrorCode = "CLIENT_UNHANDLED_ERROR",
                            Category = "Client-Side/Runtime",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "שגיאת JavaScript גלובלית בלתי צפויה בדפדפן הלקוח, מחוץ למחזור ה-render של React (למשל בתוך event handler או setTimeout) - מזוהה אוטומטית",
                            ResolutionPlaybook = "1. לבדוק את ה-Stack Trace ואת השורה המדויקת שבה קרתה השגיאה. 2. לשחזר את הפעולה שהובילה לשגיאה לפי RawPayload (URL, User Agent). 3. אם זו שגיאה חוזרת, לשקול הוספת בדיקת תקינות (guard clause) בקוד הרלוונטי.",
                            SeverityLevel = (byte)3,
                            Subsystem = "WebClient",
                            TenantId = ""
                        },
                        new
                        {
                            ErrorCode = "SERVER_UNHANDLED_EXCEPTION",
                            Category = "Server-Side/Runtime",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "חריגה בלתי צפויה נלכדה ב-GlobalExceptionHandler בשרת - קוד השתבש בדרך שלא טופלה מראש (לא NotFound/ולידציה/קונפליקט ידוע). מזוהה אוטומטית מכל בקשת API",
                            ResolutionPlaybook = "1. לבדוק את ה-Stack Trace המלא ואת סוג החריגה המדויק (RawPayload כולל את הנתיב והמתודה של הבקשה). 2. לבדוק בלוגים של Application Insights את אותו חלון זמן לפי IncidentId. 3. לתקן את הקוד ולהוסיף טיפול חריגה ספציפי ב-GlobalExceptionHandler אם מדובר בתרחיש שחוזר ועדיין ראוי ל-400/404 ולא ל-500.",
                            SeverityLevel = (byte)4,
                            Subsystem = "BackendApi",
                            TenantId = ""
                        },
                        new
                        {
                            ErrorCode = "CLIENT_UNHANDLED_REJECTION",
                            Category = "Client-Side/Runtime",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "הבטחה (Promise) בקוד הלקוח נדחתה בלי טיפול (.catch) - לרוב מעיד על קריאת API או פעולה אסינכרונית שנכשלה בלי הודעה למשתמש",
                            ResolutionPlaybook = "1. לבדוק את הודעת השגיאה ואת ה-Stack Trace אם קיים. 2. לאתר את הקריאה האסינכרונית החסרה בטיפול (fetch/Promise) ולהוסיף .catch מתאים. 3. לוודא שהמשתמש מקבל הודעת שגיאה ברורה במקום שהאפליקציה פשוט 'נתקעת' בשקט.",
                            SeverityLevel = (byte)3,
                            Subsystem = "WebClient",
                            TenantId = ""
                        },
                        new
                        {
                            ErrorCode = "CLIENT_HANDLED_API_FAILURE",
                            Category = "Client-Side/API",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "קריאת API נכשלה אך טופלה בצורה מבוקרת בממשק (המשתמש רואה הודעת שגיאה ידידותית ולא קריסה) - נשמר כדי לעקוב אחרי כשלים חוזרים שהלקוח לא בהכרח מדווח עליהם",
                            ResolutionPlaybook = "1. לבדוק את הודעת השגיאה ואת ה-URL שנקרא (RawPayload). 2. אם זו תקרית חוזרת מאותו endpoint, לבדוק את הלוגים בצד השרת לאותו חלון זמן. 3. לוודא שזו לא בעיית רשת זמנית של הלקוח בלבד לפני שפותחים חקירה מעמיקה.",
                            SeverityLevel = (byte)2,
                            Subsystem = "WebClient",
                            TenantId = ""
                        },
                        new
                        {
                            ErrorCode = "SERVER_DATABASE_UNAVAILABLE",
                            Category = "Server-Side/Database",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HebrewDescription = "בסיס הנתונים לא היה נגיש לשרת (חריגת SQL/timeout בחיבור) - נרשם זמנית בזיכרון ונשמר כתקרית קבועה ברגע שהחיבור חזר",
                            ResolutionPlaybook = "1. לבדוק ב-Azure Portal את מצב שרת ה-SQL (Firewall, DTU/vCore throttling, תחזוקה מתוכננת). 2. לבדוק את RawPayload לזמן המדויק ואת הנתיב שנכשל. 3. אם זה חוזר, לשקול Connection Pooling/Retry policy אגרסיביים יותר או שדרוג tier.",
                            SeverityLevel = (byte)4,
                            Subsystem = "SqlServer",
                            TenantId = ""
                        });
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.IncidentDetailPayload", b =>
                {
                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.ToTable("IncidentDetailPayloads", (string)null);
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.IncidentReporter", b =>
                {
                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int");

                    b.HasKey("IncidentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IncidentReporters", (string)null);
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.SystemErrorIncident", b =>
                {
                    b.Property<long>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncidentId"));

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientStationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorFingerprintHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IncidentId");

                    b.HasIndex("TenantId", "ErrorFingerprintHash")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemErrorIncidents_Tenant_Fingerprint");

                    b.ToTable("SystemErrorIncidents", (string)null);
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedOutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aharon.halevy@lawfirm.co.il",
                            FailedLoginAttempts = 0,
                            FullName = "אהרון הלוי",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEC1Wb2k1xvIBk3h4pb0eY5gJy8M01dZhT4WIsY+Wl1WfPZBZi+jUD6S7nz0/Ml9YVg==",
                            Role = (byte)2,
                            TenantId = "default-tenant"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "noa.cohen@lawfirm.co.il",
                            FailedLoginAttempts = 0,
                            FullName = "נועה כהן",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEC1Wb2k1xvIBk3h4pb0eY5gJy8M01dZhT4WIsY+Wl1WfPZBZi+jUD6S7nz0/Ml9YVg==",
                            Role = (byte)1,
                            TenantId = "default-tenant"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "itai.mizrahi@lawfirm.co.il",
                            FailedLoginAttempts = 0,
                            FullName = "איתי מזרחי",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEC1Wb2k1xvIBk3h4pb0eY5gJy8M01dZhT4WIsY+Wl1WfPZBZi+jUD6S7nz0/Ml9YVg==",
                            Role = (byte)1,
                            TenantId = "default-tenant"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shira.bendavid@lawfirm.co.il",
                            FailedLoginAttempts = 0,
                            FullName = "שירה בן-דוד",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEC1Wb2k1xvIBk3h4pb0eY5gJy8M01dZhT4WIsY+Wl1WfPZBZi+jUD6S7nz0/Ml9YVg==",
                            Role = (byte)1,
                            TenantId = "default-tenant"
                        });
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.BugReport", b =>
                {
                    b.HasOne("MyBackendApi.Models.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.IncidentDetailPayload", b =>
                {
                    b.HasOne("MyBackendApi.Models.Entities.SystemErrorIncident", "Incident")
                        .WithOne("Details")
                        .HasForeignKey("MyBackendApi.Models.Entities.IncidentDetailPayload", "IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.IncidentReporter", b =>
                {
                    b.HasOne("MyBackendApi.Models.Entities.SystemErrorIncident", "Incident")
                        .WithMany("Reporters")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackendApi.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBackendApi.Models.Entities.SystemErrorIncident", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Reporters");
                });
#pragma warning restore 612, 618
        }
    }
}
